"""expense combined link

Revision ID: 2f9b186014f8
Revises: 17cecd4591bd
Create Date: 2026-06-28 01:44:57.504613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9b186014f8'
down_revision: Union[str, None] = '17cecd4591bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combined_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_expenses_combined_id_combined_txns'), 'combined_txns', ['combined_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_expenses_combined_id_combined_txns'), type_='foreignkey')
        batch_op.drop_column('combined_id')

    # ### end Alembic commands ###
