"""expense split payers

Revision ID: 83b08bfff1bf
Revises: b047bc90f6ce
Create Date: 2026-06-27 16:43:54.029110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b08bfff1bf'
down_revision: Union[str, None] = 'b047bc90f6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_txns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loading_payer2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('loading_split', sa.Numeric(precision=5, scale=2), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('freight_payer2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('freight_split', sa.Numeric(precision=5, scale=2), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('unloading_payer2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unloading_split', sa.Numeric(precision=5, scale=2), nullable=False, server_default='100'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_txns', schema=None) as batch_op:
        batch_op.drop_column('unloading_split')
        batch_op.drop_column('unloading_payer2')
        batch_op.drop_column('freight_split')
        batch_op.drop_column('freight_payer2')
        batch_op.drop_column('loading_split')
        batch_op.drop_column('loading_payer2')

    # ### end Alembic commands ###
