"""expense split rupees

Revision ID: f53b1510ebf5
Revises: 83b08bfff1bf
Create Date: 2026-06-27 16:58:11.752417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53b1510ebf5'
down_revision: Union[str, None] = '83b08bfff1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_txns', schema=None) as batch_op:
        batch_op.alter_column('loading_split',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('freight_split',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('unloading_split',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'100'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_txns', schema=None) as batch_op:
        batch_op.alter_column('unloading_split',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('freight_split',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('loading_split',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'100'"))

    # ### end Alembic commands ###
