# ==========================================================================
#  PROMOTE THIS BACKUP PC TO "MAIN LAN SERVER" for the 5 office PCs.
#
#  Use this when Supabase is gone for good / you hit the free limit and you
#  want to run exactly like the old LAN setup (5 PCs -> this PC's PostgreSQL).
#
#  Run ONCE, in an ADMIN PowerShell, on the backup PC that holds the local
#  'timber' database (kept fresh by local-backup.ps1 / restore-and-go-local.ps1):
#      powershell -ExecutionPolicy Bypass -File .\enable-lan-server.ps1
#
#  It makes local PostgreSQL reachable over the office LAN:
#    1. listen_addresses = '*'         (accept LAN connections, not just local)
#    2. pg_hba.conf: allow the office subnet with password auth
#    3. open Windows Firewall for TCP 5432
#    4. restart the PostgreSQL service
#    5. write a ready  CLIENT-LAN.env  with THIS PC's IP for the other 4 PCs
# ==========================================================================

$ErrorActionPreference = "Stop"

# ---------- CONFIG --------------------------------------------------------
# Office LAN subnet the client PCs are on (CIDR). Adjust if yours differs.
$OfficeSubnet = "192.168.10.0/24"
# Where to drop the ready client .env (defaults next to this script).
$ClientEnvOut = Join-Path $PSScriptRoot "CLIENT-LAN.env"
# --------------------------------------------------------------------------

# 1) Locate the PostgreSQL data directory + service (newest installed version).
$pgBase = "C:\Program Files\PostgreSQL"
if (-not (Test-Path $pgBase)) { throw "PostgreSQL not found under $pgBase - install it or edit this path." }
$verDir = Get-ChildItem $pgBase -Directory | Sort-Object Name -Descending | Select-Object -First 1
$dataDir = Join-Path $verDir.FullName "data"
$conf    = Join-Path $dataDir "postgresql.conf"
$hba     = Join-Path $dataDir "pg_hba.conf"
if (-not (Test-Path $conf)) { throw "postgresql.conf not found at $conf" }
$svc = Get-Service | Where-Object { $_.Name -like "postgresql*" } | Select-Object -First 1
if (-not $svc) { throw "PostgreSQL Windows service not found." }
Write-Host "Using PostgreSQL $($verDir.Name)  (data: $dataDir, service: $($svc.Name))"

# 2) listen_addresses = '*'  (back up the file first)
Copy-Item $conf "$conf.bak" -Force
$confText = Get-Content $conf -Raw
if ($confText -match "(?m)^\s*#?\s*listen_addresses\s*=.*$") {
    $confText = $confText -replace "(?m)^\s*#?\s*listen_addresses\s*=.*$", "listen_addresses = '*'"
} else {
    $confText += "`r`nlisten_addresses = '*'`r`n"
}
Set-Content -Path $conf -Value $confText -Encoding utf8
Write-Host "[1/4] listen_addresses = '*'"

# 3) pg_hba.conf: allow the office subnet (idempotent - only add once)
Copy-Item $hba "$hba.bak" -Force
$hbaLine = "host    all    all    $OfficeSubnet    scram-sha-256"
if ((Get-Content $hba -Raw) -notmatch [regex]::Escape($OfficeSubnet)) {
    Add-Content -Path $hba -Value "`r`n# Office LAN access (added by enable-lan-server.ps1)`r`n$hbaLine`r`n"
    Write-Host "[2/4] pg_hba.conf: allowed $OfficeSubnet"
} else {
    Write-Host "[2/4] pg_hba.conf: $OfficeSubnet already allowed"
}

# 4) Windows Firewall: open TCP 5432 (idempotent)
if (-not (Get-NetFirewallRule -DisplayName "PostgreSQL 5432 (ASW LAN)" -ErrorAction SilentlyContinue)) {
    New-NetFirewallRule -DisplayName "PostgreSQL 5432 (ASW LAN)" -Direction Inbound `
        -Protocol TCP -LocalPort 5432 -Action Allow -Profile Any | Out-Null
    Write-Host "[3/4] Firewall: opened TCP 5432"
} else {
    Write-Host "[3/4] Firewall: TCP 5432 already open"
}

# 5) Restart PostgreSQL so the config takes effect
Restart-Service $svc.Name
Write-Host "[4/4] PostgreSQL restarted."

# --- Write a ready client .env with THIS PC's LAN IP -----------------------
$ip = (Get-NetIPAddress -AddressFamily IPv4 |
       Where-Object { $_.IPAddress -like "192.168.*" -or $_.IPAddress -like "10.*" } |
       Select-Object -First 1).IPAddress
if (-not $ip) { $ip = "<THIS-PC-LAN-IP>" }

@"
# Auto-generated by enable-lan-server.ps1 - copy to each of the other PCs as .env
# (into the exe folder), then paste the local Postgres password below.
TIMBER_DB_BACKEND=postgresql
TIMBER_PG_HOST=$ip
TIMBER_PG_PORT=5432
TIMBER_PG_USER=timber
TIMBER_PG_PASSWORD=PASTE-LOCAL-POSTGRES-PASSWORD-HERE
TIMBER_PG_DB=timber
TIMBER_PG_SSLMODE=
TIMBER_PG_CONNECT_TIMEOUT=8
TIMBER_PG_STATEMENT_TIMEOUT=30000
TIMBER_AUDIT_RETENTION_DAYS=3
TIMBER_SEED_MASTER_DATA=0
TIMBER_LANG=ur
"@ | Set-Content -Path $ClientEnvOut -Encoding utf8

Write-Host ""
Write-Host "DONE. This PC is now the LAN database server at IP: $ip"
Write-Host "Client .env written to: $ClientEnvOut"
Write-Host "On each other PC: copy that file to the exe folder as .env, paste the local Postgres password, launch."
