"""cheques and loans

Revision ID: 1b5e984e3641
Revises: 2f9b186014f8
Create Date: 2026-06-29 11:01:06.924444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5e984e3641'
down_revision: Union[str, None] = '2f9b186014f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('lender_name', sa.String(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_loans_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_loans_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_table('loan_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_loan_repayments_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_loan_repayments_created_by_users')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_repayments_loan_id_loans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_repayments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cheque_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cleared_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('cleared_date')
        batch_op.drop_column('cheque_status')

    op.drop_table('loan_repayments')
    op.drop_table('loans')
    # ### end Alembic commands ###
