"""payment party bank

Revision ID: 28e773c57c81
Revises: 44756931076a
Create Date: 2026-06-25 01:48:53.605985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e773c57c81'
down_revision: Union[str, None] = '44756931076a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party_bank_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_party_bank_id_party_banks'), 'party_banks', ['party_bank_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_party_bank_id_party_banks'), type_='foreignkey')
        batch_op.drop_column('party_bank_id')

    # ### end Alembic commands ###
