"""bapari-factory links

Revision ID: 38ac4b684be9
Revises: eb94448b70ab
Create Date: 2026-06-14 23:50:31.005956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ac4b684be9'
down_revision: Union[str, None] = 'eb94448b70ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_links',
    sa.Column('bapari_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bapari_id'], ['parties.id'], name=op.f('fk_party_links_bapari_id_parties')),
    sa.ForeignKeyConstraint(['factory_id'], ['parties.id'], name=op.f('fk_party_links_factory_id_parties')),
    sa.PrimaryKeyConstraint('bapari_id', 'factory_id', name=op.f('pk_party_links'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_links')
    # ### end Alembic commands ###
