"""account transfers

Revision ID: 44756931076a
Revises: 578fb0883dc1
Create Date: 2026-06-15 00:42:38.344593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44756931076a'
down_revision: Union[str, None] = '578fb0883dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_account_transfers_created_by_users')),
    sa.ForeignKeyConstraint(['from_account_id'], ['bank_accounts.id'], name=op.f('fk_account_transfers_from_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['to_account_id'], ['bank_accounts.id'], name=op.f('fk_account_transfers_to_account_id_bank_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_transfers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_transfers')
    # ### end Alembic commands ###
