"""trade group id

Revision ID: b047bc90f6ce
Revises: 67bbf84e652a
Create Date: 2026-06-27 10:58:20.156415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b047bc90f6ce'
down_revision: Union[str, None] = '67bbf84e652a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_txns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_txns', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
