"""initial schema

Revision ID: eb94448b70ab
Revises: 
Create Date: 2026-06-14 23:33:35.839386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb94448b70ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('name', name=op.f('uq_bank_accounts_name'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('name', name=op.f('uq_locations_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('wood_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wood_types')),
    sa.UniqueConstraint('name', name=op.f('uq_wood_types_name'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_expenses_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expenses_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_parties_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties'))
    )
    op.create_table('bapari_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('wood_type_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_no', sa.String(), nullable=True),
    sa.Column('muds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bapari_txns_created_by_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_bapari_txns_location_id_locations')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_bapari_txns_party_id_parties')),
    sa.ForeignKeyConstraint(['wood_type_id'], ['wood_types.id'], name=op.f('fk_bapari_txns_wood_type_id_wood_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bapari_txns'))
    )
    op.create_table('factory_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('wood_type_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_no', sa.String(), nullable=True),
    sa.Column('muds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_factory_txns_created_by_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_factory_txns_location_id_locations')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_factory_txns_party_id_parties')),
    sa.ForeignKeyConstraint(['wood_type_id'], ['wood_types.id'], name=op.f('fk_factory_txns_wood_type_id_wood_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factory_txns'))
    )
    op.create_table('party_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('account_title', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_banks_party_id_parties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_banks'))
    )
    op.create_table('party_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_phones_party_id_parties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_phones'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_payments_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payments_created_by_users')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_payments_party_id_parties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_table('combined_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('bapari_txn_id', sa.Integer(), nullable=False),
    sa.Column('factory_txn_id', sa.Integer(), nullable=False),
    sa.Column('loading_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loading_payer', sa.String(), nullable=False),
    sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_payer', sa.String(), nullable=False),
    sa.Column('unloading_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unloading_payer', sa.String(), nullable=False),
    sa.Column('own_expense', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bapari_txn_id'], ['bapari_txns.id'], name=op.f('fk_combined_txns_bapari_txn_id_bapari_txns')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_combined_txns_created_by_users')),
    sa.ForeignKeyConstraint(['factory_txn_id'], ['factory_txns.id'], name=op.f('fk_combined_txns_factory_txn_id_factory_txns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combined_txns'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combined_txns')
    op.drop_table('payments')
    op.drop_table('party_phones')
    op.drop_table('party_banks')
    op.drop_table('factory_txns')
    op.drop_table('bapari_txns')
    op.drop_table('parties')
    op.drop_table('expenses')
    op.drop_table('audit_log')
    op.drop_table('wood_types')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
